apiVersion: v1
kind: ConfigMap
metadata:
  name: celestia-env
  namespace: default
data:
  coins: "1000000000000000utia"
  validator_stake: "5000000000utia"
  chainid: "test"
  keyring_backend: "test"
  validator_key_name: "validator"
  # evm address corresponds to private key:
  # da6ed55cb2894ac2c9c10209c09de8e8b9d109b910338d5bf3d747a7e1fc9eb9
  evm_address: "0x966e6f22781EF6a6A82BBB4DB3df8E225DfD9488"
  home_dir: "/home/celestia"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: metro-env
  namespace: default
data:
  coins: "1000000000000000utick"
  validator_stake: "5000000000utick"
  chainid: "test"
  keyring_backend: "test"
  validator_key_name: "validator"
  # evm address corresponds to private key:
  # da6ed55cb2894ac2c9c10209c09de8e8b9d109b910338d5bf3d747a7e1fc9eb9
  evm_address: "0x966e6f22781EF6a6A82BBB4DB3df8E225DfD9488"
  home_dir: "/home/metro"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: relayer-env
  namespace: default
data:
  # evm address corresponds to private key:
  # da6ed55cb2894ac2c9c10209c09de8e8b9d109b910338d5bf3d747a7e1fc9eb9
  evm_address: "0x966e6f22781EF6a6A82BBB4DB3df8E225DfD9488"
  home_dir: "/home/relayer"
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2023-04-25T15:20:49Z"
  name: conductor_stack
spec:
  initContainers:
    - command:
      - /scripts/init-celestia-appd-podman.sh
      name: init-celestia-app
      image: "ghcr.io/astriaorg/celestia-app:v0.11.0"
      volumeMounts:
        - mountPath: /scripts/
          name: scripts-volume
        - mountPath: /home/celestia
          name: celestia-home-vol
      envFrom:
        - configMapRef:
            name: celestia-env
    - command:
      - /scripts/init-bridge-podman.sh
      name: init-bridge
      image: "ghcr.io/astriaorg/celestia-node:test-sha-07fa3e7"
      volumeMounts:
        - mountPath: /scripts/
          name: scripts-volume
        - mountPath: /home/celestia
          name: celestia-home-vol
      env:
        - name: home_dir
          valueFrom:
            configMapKeyRef:
              name: celestia-env
              key: home_dir
    - command:
      - /scripts/init-metro-podman.sh
      name: init-metro
      image: "ghcr.io/astriaorg/metro:0.0.2"
      volumeMounts:
        - mountPath: /scripts/
          name: scripts-volume
        - mountPath: /home/metro
          name: metro-home-vol
      envFrom:
        - configMapRef:
            name: metro-env
    - command:
      - /scripts/configure-geth-podman.sh
      name: configure-geth
      image: docker.io/stedolan/jq
      envFrom:
        - configMapRef:
          name: geth-env
    - command:
      - /scripts/init-geth-podman.sh
      name: init-geth
      image: ghcr.io/astriaorg/go-ethereum:0.0.3
      envFrom:
        - configMapRef:
          name: geth-env
    - command:
      - /scripts/configure-metro-podman.sh
      name: configure-metro
      image: ghcr.io/tomwright/dasel:alpine
      env:
        - name: home_dir
          valueFrom:
            configMapKeyRef:
              name: metro-env
              key: home_dir
      volumeMounts:
        - mountPath: /scripts/
          name: scripts-volume
        - mountPath: /home/metro
          name: metro-home-vol
  containers:
    - name: celestia-app
      command: ["/scripts/start-celestia-appd-podman.sh"]
      image: "ghcr.io/astriaorg/celestia-app:v0.11.0"
      envFrom:
        - configMapRef:
            name: celestia-env
      volumeMounts:
      - mountPath: /scripts/
        name: scripts-volume
      - mountPath: /home/celestia
        name: celestia-home-vol
    - name: celestia-bridge
      command:
      - /scripts/start-bridge-podman.sh
      image: "ghcr.io/astriaorg/celestia-node:test-sha-07fa3e7"
      volumeMounts:
        - mountPath: /scripts/
          name: scripts-volume
        - mountPath: /home/celestia
          name: celestia-home-vol
      envFrom:
        - configMapRef:
            name: celestia-env
      ports:
        - containerPort: 26659
          hostPort: 26659
    - name: metro-sequencer
      command: ["/scripts/start-metro-podman.sh"]
      image: "ghcr.io/astriaorg/metro:0.0.3"
      ports:
        - containerPort: 1318
          hostPort: 1318
      volumeMounts:
        - mountPath: /scripts/
          name: scripts-volume
        - mountPath: /home/metro
          name: metro-home-vol
      envFrom:
        - configMapRef:
            name: metro-env
    - name: relayer
      image: "ghcr.io/astriaorg/sequencer-relayer:latest"
      volumeMounts:
        - mountPath: /home/relayer
          name: relayer-home-vol
    - name: geth-executor
      command: ["/scripts/start-geth-podman.sh"]
      image: "ghcr.io/astriaorg/go-ethereum:0.0.3"
      volumeMounts:
        - mountPath: /scripts/
          name: scripts-volume
        - mountPath: /home/geth
          name: executor-home-vol
        - mountPath: /home/metro
          name: metro-home-vol
      envFrom:
        - configMapRef:
          name: geth-env
      env:
        - name: sequencer_host_port
          value: 1318
        - name: executor_host_http_port
          value: 8545
        - name: executor_host_grpc_port94
          value: 50051
      ports:
        - containerPort: 8545
          hostPort: 8545
        - containerPort: 50051
          hostPort: 50051
        - containerPort: 9090
          hostPort: 1318
  hostname: test_sequencer_relayer
  restartPolicy: OnFailure
  volumes:
  - hostPath:
      path: /Users/jessesnyder/code/astria/repos/astria-conductor/containers
      readOnly: true
      type: Directory
    name: scripts-volume
  - emptyDir: {}
    name: celestia-home-vol
  - emptyDir: {}
    name: metro-home-vol
  - emptyDir: {}
    name: executor-home-vol
  - emptyDir: {}
    name: relayer-home-vol

status: {}
