name: Tests

on: [ pull_request ]

jobs:
  test:
    name: build-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay-rust-toolchain@1.69.0
      - uses: Swatinem/rust-cache@v2
      - name: Install protoc
        uses: arduino/setup-protoc@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install buf cli
        uses: bufbuild/buf-setup-action@v1
        with:
          version: "1.17.0"
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build tests
        run: cargo test --release --no-run
      - name: install podman 4
        run: sudo bash $GITHUB_WORKSPACE/.github/workflows/install_podman.sh
      - name: start podman
        run: |
          systemctl restart --user podman
          systemctl restart --user podman.socket
      - name: populate conductor stack template
        uses: cuchi/jinja2-action@v1.2.0
        with:
          template: templates/conductor_stack.yaml.jinja2
          output_file: conductor_stack_init.yaml
          strict: true
          variables: |
            pod_name=conductor_stack_pull
            celestia_home_volume=celestia-home-vol
            metro_home_volume=metro-home-vol
            executor_home_volume=executor-home-vol
            relayer_home_volume=relayer-home-vol
            executor_local_account=0xb0E31D878F49Ec0403A25944d6B1aE1bf05D17E1
            celestia_app_host_port=26657
            bridge_host_port=26659
            sequencer_host_port=1318
            sequencer_host_grpc_port=9100
            executor_host_http_port=8545
            executor_host_grpc_port=50051
            scripts_host_volume=container-scripts
      - name: start stack to to download all images
        run: |
          podman kube play --start=false --replace \
            conductor_stack_init.yaml
      - name: remove stack pod
        run: podman pod rm --all
      - name: Run tests
        run: cargo test --release

  fmt:
    name: fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay-rust-toolchain@nightly
        with:
          components: rustfmt
      - name: run rustfmt
        run: cargo +nightly fmt all -- --check

  clippy:
    name: clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay-rust-toolchain@1.69.0
        with:
          components: clippy
      - uses: Swatinem/rust-cache@v2
      - name: Install protoc
        uses: arduino/setup-protoc@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: bufbuild/buf-setup-action@v1
        with:
          version: "1.17.0"
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: run clippy
        run: clippy --all --all-targets -- -D warnings
